version: '3.8'

services:
  newsbuddy:
    container_name: NB
    image: newsbuddy
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./data/logs:/app/data/logs
    links: 
      - postgres
  
  postgres:
    image: postgres
    container_name: postgres
    environment: 
      POSTGRES_DB: newsbuddy_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/db
    volumes:
      - ./data/db:/data/db
      - ./news_buddy/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 9696:5432