version: '3.8'

services:

  database:
    image: postgres
    container_name: postgres_database
    env_file:
      - .env
    volumes:
      - ./data/db:/data/db
      - ./news_buddy/initdb/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 9696:5432

  newsbuddy:
    container_name: newsbuddy
    image: newsbuddy
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./data/logs:/app/data/logs
    depends_on: 
      - database
    env_file:
      - .env