version: '3.4'

services:
  newsbuddy:
    container_name: NB
    image: newsbuddy
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./data/logs:/app/data/logs
    depends_on: 
      - postgres
  
  postgres:
    image: postgres
    container_name: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: newsbuddy_db
      PGDATA: /data/db
    volumes:
      - ./data/db:/data/db
      - ./news_buddy/initdb:/docker-entrypoint-initdb.d
    ports:
      - 9696:5432